use CSE_3B_364
--PARTA
CREATE TABLE CRICKET(
NAME VARCHAR(50),
CITY VARCHAR (50),
AGE INT);
 INSERT INTO CRICKET VALUES ('Sachin Tendulkar', 'Mumbai', 30);
INSERT INTO CRICKET VALUES ('Rahul Dravid',' Bombay', 35);
INSERT INTO CRICKET VALUES ('M. S. Dhoni', 'Jharkhand', 31);
INSERT INTO CRICKET VALUES ('Suresh Raina', 'Gujarat', 30);
SELECT *INTO WORLDCUP FROM CRICKET;
SELECT NAME,CITY INTO T20 FROM CRICKET WHERE 1=0;                                          
SELECT *FROM WORLDCUP;
ALTER TABLE T20 DROP COLUMN AGE;
SELECT *INTO IPL FROM CRICKET WHERE 1=0;
--PARTB
CREATE TABLE EMPLOYEE(
NAME VARCHAR(50),
CITY VARCHAR(50),
AGE INT
);
INSERT INTO EMPLOYEE VALUES('Jay Patel', 'Rajkot', 30);
INSERT INTO EMPLOYEE VALUES('Rahul Dave', 'Baroda ',35);
INSERT INTO EMPLOYEE VALUES('Jeet Patel ','Surat ',31);
INSERT INTO EMPLOYEE VALUES('Vijay Raval', 'Rajkot', 30);
 select *into Employee_detail FROM EMPLOYEE;
 SELECT NAME,CITY INTO Employee_data FROM EMPLOYEE WHERE 1=0;
 SELECT *INTO Employee_info FROM EMPLOYEE WHERE 1=0;

--PART C
INSERT INTO Employee_info SELECT *FROM EMPLOYEE WHERE CITY='RAJKOT';
INSERT INTO Employee_info SELECT *FROM EMPLOYEE WHERE AGE>32;

SELECT *FROM Employee_info;