--PART A
SELECT CNAME,ACTNO,AMOUNT FROM   DEPOSIT
 SELECT LOANNO,AMOUNT FROM BORROW\
 SELECT *FROM DEPOSIT 
SELECT *FROM BORROW
 SELECT *FROM CUSTOMERS
 SELECT *FROM BORROW WHERE BNAME='ANDHERI'
 SELECT CNAME,AMOUNT FROM DEPOSIT WHERE ACTNO=106
 SELECT CNAME FROM BORROW WHERE AMOUNT>5000
  SELECT CNAME FROM DEPOSIT WHERE ADATE>'1996-12-1'
   SELECT CNAME FROM DEPOSIT WHERE ACTNO<105
--PARTR5 B
SELECT CANME FROM CUSTOMERS WHERE CITY='NAGPUR' OR CITY='DELHI';
SELECT CNAME,BNAME FROM DEPOSIT WHERE AMOUNT>4000 AND ACTNO<105;
SELECT CNAME FROM BORROW WHERE AMOUNT>=3000 AND AMOUNT<=8000;
SELECT CNAME FROM BORROW WHERE AMOUNT BETWEEN 3000 AND 8000;
SELECT *FROM DEPOSIT WHERE BNAME <>'ANDHERI';
SELECT ACTNO,CNAME,AMOUNT FROM DEPOSIT WHERE BNAME IN('AJNI','KAROLBAGH','M.G ROAD') AND ACTNO<104;
SELECT*FROM DEPOSIT
SELECT TOP 5 *FROM DEPOSIT;
SELECT TOP 3 *FROM DEPOSIT WHERE AMOUNT>1000;
SELECT  TOP 5 LOANNO,CNAME FROM BORROW WHERE BNAME <> 'ANDHERI';
SELECT  DISTINCT CITY FROM CUSTOMERS ; 
SELECT DISTINCT BNAME FROM BRANCH;
SELECT TOP 50 PERCENT AMOUNT FROM BORROW;
SELECT TOP 25 PERCENT CNAME FROM DEPOSIT WHERE AMOUNT>5000;  
SELECT TOP 10 PERCENT AMOUNT FROM BORROW ;  
SELECT DISTINCT CNAME,BNAME FROM DEPOSIT; 
SELECT AMOUNT,AMOUNT+ AMOUNT *0.1 AS NEW_AMOUNT FROM BORROW; 
SELECT *FROM BORROW WHERE LOANNO%2=0; 
SELECT *FROM BORROW WHERE LOANNO%2<>0;
