--PART A

UPDATE  DEPOSIT SET AMOUNT=5000 WHERE AMOUNT=3000;
SELECT *FROM DEPOSIT;
UPDATE BORROW SET BNAME='C.G ROAD' WHERE  CNAME='ANIL';
SELECT *FROM BORROW;
UPDATE DEPOSIT SET ACTNO=111 , AMOUNT=500 WHERE CNAME='SANDEEP';
UPDATE DEPOSIT SET AMOUNT =7000 WHERE CNAME='KRANTI';
UPDATE BRANCH SET BNAME='ANDHERI ' WHERE BNAME='ANDHERI WEST';
UPDATE DEPOSIT SET BNAME='NEHRU PALACE' WHERE CNAME='MEHUL';
UPDATE DEPOSIT SET AMOUNT=5000 WHERE ACTNO  BETWEEN 103 AND 107; 
UPDATE DEPOSIT SET ADATE='1995-4-1' WHERE CNAME='ANIL';
UPDATE DEPOSIT SET AMOUNT=7000 WHERE CNAME='MINU';
UPDATE DEPOSIT SET AMOUNT=5000,ADATE='1996-4=1' WHERE CNAME='PRAMOD';

--PARTB

UPDATE BORROW SET AMOUNT=(AMOUNT+0.1*AMOUNT) ;
UPDATE DEPOSIT SET AMOUNT=(AMOUNT+AMOUNT*0.2);

--partc
UPDATE BORROW SET AMOUNT=NULL WHERE LOANNO=321; 
UPDATE BORROW SET BNAME=NULL WHERE CNAME='KRANTI'; 
SELECT CNAME FROM BORROW WHERE AMOUNT IS NULL;
SELECT CNAME FROM BORROW WHERE BNAME IS NOT NULL;
UPDATE BORROW SET AMOUNT=5000 ,BNAME='VREC' ,CNAME='DARSHAN' WHERE LOANNO=481; 
UPDATE DEPOSIT SET ADATE='2021-01-01' WHERE AMOUNT<2000;
UPDATE DEPOSIT SET ADATE=NULL ,BNAME='ANDHERI' WHERE ACTNO=110